# © 2024 INRAE
# SPDX-FileContributor: Marcellino Palerme <marcellino.palerme@inrae.fr>
#
# SPDX-License-Identifier: MIT

name: publish

on:
  pull_request:
    branches: 'main'

permissions: 
  contents: write
  pull-requests: write
  checks: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.MY_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -f DockerfileQuay -t ghcr.io/${{ github.repository }}:latest -t ghcr.io/${{ github.repository }}:1.7.1 .

    - name: Push Docker image
      run: |
        docker push -a ghcr.io/${{ github.repository }}